ssh_proxy_opts: "-nNT -o ServerAliveInterval=15 -o ServerAliveCountMax=4 -o GatewayPorts=yes" 

# Пользователь от которого будут устанавливаться ssh proxy соединения
# Также этот пользователь будет хранить ключи для установки ssh соединений
ssh_proxy_user: "{{ common_user | d(ansible_user_id) }}" 

ssh_proxy_autokey: true         # Автоматическая генерация и управление ключами ssh
ssh_proxy_add_known_hosts: true # Добавлять sshd хост в known_hosts

ssh_proxy: {}   # noqa var-naming[no-role-prefix]

# Описание параметров
# -------------------
# ssh_proxy:
#   example:                          # Имя прокси (используется в наименовании systemd.service)
#     type  : forward|reverse|socks   # Тип прокси
#     state : present|absent          # Добавить (present) / Удалить (absent) (по-умолчанию - present)
#     remote: 0.0.0.0:2022            # адрес:порт на локальной системе (не используется для socks-proxy)
#     local : localhost:22            # адрес:порт на удаленной системе
#     sshd  : user@outpost            # подключение к удаленному ssh-серверу
#     port  : 2222                    # порт для подключения к ssh



