---
- name: Ssh key configuration (auto)
  when: ssh_proxy_autokey
  ansible.builtin.include_role:
    name: x
    tasks_from: ssh_gen_key.yml
  vars:
    x_user  : "{{ ssh_proxy_user }}"
    x_key   : "{{ ssh_proxy_item.key }}"
    x_copyto: "{{ ssh_proxy_item.value.sshd }}"

- name: "{{ ssh_proxy_item.key }} | Add to known_hosts"
  when: ssh_proxy_add_known_hosts
  become: true
  become_user: "{{ ssh_proxy_user }}"
  ansible.builtin.known_hosts:
    name: "{{ name_host }}"  # IP/домен целевого хоста
    key: "{{ lookup('pipe', 'ssh-keyscan -p {{ ssh_port }} {{ remote_host }}') }}"
    path: "{{ known_hosts_path | default('~/.ssh/known_hosts') }}"
  vars:
    remote_host: "{{ ssh_proxy_item.value.sshd.split('@')[1] }}"  # Замените на ваш хост
    ssh_port: "{{ ssh_proxy_item.value.port | default(22) }}"
    name_host: "{{ '[' ~ remote_host ~ ']:' ~ ssh_port if ssh_port != 22 else remote_host }}"  

- name: "{{ ssh_proxy_item.key }} | Create service"
  ansible.builtin.template:
    src   : "ssh_proxy.service.j2"
    dest  : "/etc/systemd/system/ssh_proxy_{{ ssh_proxy_item.key }}.service"
    owner : "root"
    group : "root"
    mode  : "0644"
  register: res_service

- name: "{{ ssh_proxy_item.key }} | Restart service"
  when: res_service is changed or ssh_gen_key.changed
  ansible.builtin.systemd:
    daemon_reload: true
    name    : "ssh_proxy_{{ ssh_proxy_item.key }}"
    enabled : true
    state   : restarted
