---
- name: "{{ ssh_proxy_item.key }} | Stop service"
  ansible.builtin.systemd:
    daemon_reload: true
    name    : "ssh_proxy_{{ ssh_proxy_item.key }}"
    enabled : false
    state   : stopped
  register: res_service
  failed_when: false

- name: "{{ ssh_proxy_item.key }} | Remove service"
  ansible.builtin.file:
    path  : "/etc/systemd/system/ssh_proxy_{{ ssh_proxy_item.key }}.service"
    state : absent
  register: res_file

- name: "{{ ssh_proxy_item.key }} | Reload systemd daemon"
  when: res_service is changed or res_file is changed
  ansible.builtin.systemd:
    daemon_reload: true