#!/bin/sh
AFICK="/usr/bin/afick.pl"
PATH="/bin:/usr/bin"
LOGDIR="/var/log/afick"
LOGFILE="$LOGDIR/afick.log"
ERRORLOG="$LOGDIR/error.log"
CONFFILE="/etc/afick.conf"
treat_log() {
	if [ -n "$VERBOSE_AFICK" ]
	then
		echo "# This is an automated report generated by Another File Integrity Checker on $FQDN $DATE."
	fi
	if [ -s $LOGFILE ]; then
		loglines=`wc -l $LOGFILE | awk '{ print $1 }'`
		if [ ${loglines:=0} -gt $LINES ]; then
			echo "# TRUNCATED (!) output of the daily afick run:"
			echo "# Output is $loglines lines, truncated to $LINES."
			head -$LINES $LOGFILE
			echo "# The full output can be found in $LOGFILE."
		else
			echo "# Output of the daily afick run:"
			cat $LOGFILE
		fi
	elif [ -n "$VERBOSE_AFICK" ]
	then
		echo "# afick detected no changes."
	fi
	if [ -s $ERRORLOG ]; then
		errorlines=`wc -l $ERRORLOG | awk '{ print $1 }'`
		if [ ${errorlines:=0} -gt $LINES ]; then
			echo "# TRUNCATED (!) output of errors produced:"
			echo "# Error output is $errorlines lines, truncated to $LINES."
			head -$LINES $ERRORLOG
			echo "# The full output can be found in $ERRORLOG."
		else
			echo "# Errors produced:"
			cat $ERRORLOG
		fi
	elif [ -n "$VERBOSE_AFICK" ]
	then
		echo "# afick produced no errors."
	fi
	if [ -s $LOGFILE ]; then
		summary=` grep "MD5 hash of" $LOGFILE `
		if [ -z "$summary" ]
		then
			echo "WARNING: truncated report (no summary)"
		fi
	fi
}
macro () {
	key=$1
	grep "^@@define $key" $CONFFILE | head -1 | awk '{ print $3 }'
}
[ -x $AFICK ] || exit 0
FQDN=`hostname -f 2> /dev/null`
DATE=`date +"at %X on %x"`
LINES=`macro LINES`
VERBOSE=`macro VERBOSE`
REPORT=`macro REPORT`
NICE=`macro NICE`
BATCH=`macro BATCH`
[ -z "$FQDN" ] && FQDN=`hostname`
[ -z "$LINES" ] && LINES="1000"
[ -z "$VERBOSE" ] && VERBOSE=0
[ -z "$REPORT" ] && REPORT=1
[ -z "$NICE" ] && NICE=15
[ -z "$BATCH" ] && BATCH=1

if [ "$BATCH" = "0" ]
then
	exit 0
fi
if [ "$VERBOSE" = "1" ]
then
	export VERBOSE_AFICK=1
fi
nice -n $NICE $AFICK -c $CONFFILE -k > $LOGFILE 2>$ERRORLOG
if [ "$REPORT" = "0" ]
then
	# no report
	exit
fi
OUTPUT=$( treat_log  )
if [ "$VERBOSE" = "1" ]
then
	echo "$OUTPUT"
else
	OUTPUT_FILTRE=$( echo "$OUTPUT" | grep -v "^#" | grep -v "^$"  )
	if [ -n "$OUTPUT_FILTRE" ]
	then
		echo $OUTPUT_FILTRE
		echo ", "
		sh /etc/afick/send_to_zabbix.sh #отправляем информацию о файлах непрошедщих проверку в zabbix
		echo "afick_integrity_check" > /etc/afick/blocked_groups.list
	fi
fi
exit 0
