---
- name: Ðœake grub
  ansible.builtin.shell: grub-mkconfig && update-grub
  changed_when: true

- name: Reload sysctl
  ansible.builtin.command: sysctl --system
  become: true
  changed_when: true
