zbx_path: /opt/apps/zbx
zbx_user: zbx
zbx_uid : 1997
zbx_gid : 1995

zbx_db        : true
zbx_db_pgadmin: true
zbx_srv       : true
zbx_snmptraps : true
zbx_web       : true

zbx_db_image        : "timescale/timescaledb:2.15.0-pg16"
zbx_pgadmin_image   : "dpage/pgadmin4:6.14"
zbx_srv_image       : "zabbix/zabbix-server-pgsql:latest"
zbx_web_image       : "zabbix/zabbix-web-nginx-pgsql:latest"
zbx_snmptraps_image : "zabbix/zabbix-snmptraps:latest"

zbx_snmptraps_port    : 162
zbx_snmptraps_volumes : []

# Подключать БД к внешней сети?
zbx_db_front_net: false     
zbx_db_ip       : zbx_db           
zbx_db_port     : 5432
zbx_db_schema   : public
zbx_db_name     : zabbix
zbx_db_user     : zabbix
zbx_db_password : "{{ lookup('env', 'PASSWORD_DEFAULT') }}"

# Разделяемая память
zbx_db_shm_size         : 1g
# Параметр БД max_connections
zbx_db_max_connections  : 1000

zbx_pgadmin_port    : 5050
zbx_pgadmin_email   : admin@home.local
zbx_pgadmin_password: "{{ lookup('env', 'PASSWORD_DEFAULT') }}"

zbx_web_https: false
zbx_web_volumes:
  - ./ssl:/etc/ssl/nginx:ro
  - ./modules/:/usr/share/zabbix/modules/:ro

zbx_web_env: |
  ZBX_SERVER_HOST={{ zbx_srv_ip }}
  ZBX_SERVER_PORT={{ zbx_srv_port }}
  # ZBX_DB_ENCRYPTION=true # Available since 5.0.0
  # ZBX_DB_KEY_FILE=/run/secrets/client-key.pem # Available since 5.0.0
  # ZBX_DB_CERT_FILE=/run/secrets/client-cert.pem # Available since 5.0.0
  # ZBX_DB_CA_FILE=/run/secrets/root-ca.pem # Available since 5.0.0
  # ZBX_DB_VERIFY_HOST=false # Available since 5.0.0
  # ZBX_DB_CIPHER_LIST= # Available since 5.0.0
  # ZBX_VAULT= # Available since 6.2.0
  # ZBX_VAULTDBPATH=
  # ZBX_VAULTURL=https://127.0.0.1:8200
  # VAULT_TOKEN=
  # ZBX_VAULTCERTFILE= # Available since 6.2.0
  # ZBX_VAULTKEYFILE= # Available since 6.2.0
  # ZBX_VAULTCACHE=false # Available since 6.2.0
  # ZBX_HISTORYSTORAGEURL=http://elasticsearch:9200/ # Available since 3.4.5
  # ZBX_HISTORYSTORAGETYPES=['uint', 'dbl', 'str', 'text', 'log'] # Available since 3.4.5
  # ZBX_SSO_SETTINGS=[] # Available since 5.0.0
  # ENABLE_WEB_ACCESS_LOG=true
  ZBX_MAXEXECUTIONTIME=600
  ZBX_MEMORYLIMIT=128M
  ZBX_POSTMAXSIZE=16M
  ZBX_UPLOADMAXFILESIZE=2M
  ZBX_MAXINPUTTIME=300
  # ZBX_SESSION_NAME=zbx_sessionid
  # Timezone one of: http://php.net/manual/en/timezones.php
  PHP_TZ=Asia/Vladisvostok
  # ZBX_DENY_GUI_ACCESS=false
  # ZBX_GUI_ACCESS_IP_RANGE=['127.0.0.1']
  # ZBX_GUI_WARNING_MSG=Zabbix is under maintenance.
  # HTTP_INDEX_FILE=index.php
  # EXPOSE_WEB_SERVER_INFO=on

  PHP_FPM_PM=dynamic
  PHP_FPM_PM_MAX_CHILDREN=50
  PHP_FPM_PM_START_SERVERS=5
  PHP_FPM_PM_MIN_SPARE_SERVERS=5
  PHP_FPM_PM_MAX_SPARE_SERVERS=35
  PHP_FPM_PM_MAX_REQUESTS=0

zbx_srv_ip  : zbx_srv
zbx_srv_port: 10051

zbx_srv_ulimits_nproc       : 65535 
zbx_srv_ulimits_nofile_soft : 20000
zbx_srv_ulimits_nofile_hard : 40000

zbx_srv_cap_add_net_raw: false
zbx_srv_sysctls:
  - net.ipv4.ip_local_port_range=1024 64999
  - net.ipv4.conf.all.accept_redirects=0
  - net.ipv4.conf.all.secure_redirects=0
  - net.ipv4.conf.all.send_redirects=0
#   - net.ipv4.ping_group_range=0 1995

zbx_srv_volumes:
  - ./enc:/var/lib/zabbix/enc:ro
  - ./ssh_keys:/var/lib/zabbix/ssh_keys:ro
  - ./alertscripts:/usr/lib/zabbix/alertscripts:ro
  - ./externalscripts:/usr/lib/zabbix/externalscripts:ro
  - ./dbscripts:/var/lib/zabbix/dbscripts:ro
  - ./modules:/var/lib/zabbix/modules:ro

zbx_srv_env: |
  # ZBX_LISTENIP=
  # ZBX_LISTENBACKLOG=
  # ZBX_HISTORYSTORAGEURL=http://elasticsearch:9200/ # Available since 3.4.5
  # ZBX_HISTORYSTORAGETYPES=uint,dbl,str,log,text # Available since 3.4.5
  # ZBX_ALLOWUNSUPPORTEDDBVERSIONS=0 # Available since 6.0.0
  # ZBX_DBTLSCONNECT=required # Available since 5.0.0
  # ZBX_DBTLSCAFILE=/run/secrets/root-ca.pem # Available since 5.0.0
  # ZBX_DBTLSCERTFILE=/run/secrets/client-cert.pem # Available since 5.0.0
  # ZBX_DBTLSKEYFILE=/run/secrets/client-key.pem # Available since 5.0.0
  # ZBX_DBTLSCIPHER= # Available since 5.0.0
  # ZBX_DBTLSCIPHER13= # Available since 5.0.0
  # ZBX_AUTOHANODENAME=fqdn # Allowed values: fqdn, hostname. Available since 6.0.0
  # ZBX_HANODENAME= # Available since 6.0.0
  # ZBX_AUTONODEADDRESS=fqdn # Allowed values: fqdn, hostname. Available since 6.0.0
  # ZBX_NODEADDRESSPORT=10051 # Allowed to use with ZBX_AUTONODEADDRESS variable only. Available since 6.0.0
  # ZBX_NODEADDRESS=localhost:10051 # Available since 6.0.0
  ZBX_DEBUGLEVEL=3
  ZBX_STARTPOLLERS=3
  ZBX_IPMIPOLLERS=0
  ZBX_STARTPREPROCESSORS=3
  ZBX_STARTCONNECTORS=1
  ZBX_STARTPOLLERSUNREACHABLE=1
  ZBX_STARTTRAPPERS=1
  ZBX_STARTPINGERS=1
  ZBX_STARTDISCOVERERS=1
  ZBX_STARTODBCPOLLERS=0
  ZBX_STARTHTTPPOLLERS=1
  ZBX_STARTHISTORYPOLLERS=3
  ZBX_STARTTIMERS=1
  ZBX_STARTESCALATORS=1
  ZBX_STARTALERTERS=1
  ZBX_STARTLLDPROCESSORS=1
  # ZBX_JAVAGATEWAY_ENABLE=true
  # ZBX_JAVAGATEWAY=zabbix-java-gateway
  # ZBX_JAVAGATEWAYPORT=10052
  ZBX_STARTJAVAPOLLERS=0
  ZBX_STARTVMWARECOLLECTORS=0
  # ZBX_VMWAREFREQUENCY=60
  # ZBX_VMWAREPERFFREQUENCY=60
  # ZBX_VMWARECACHESIZE=8M
  # ZBX_VMWARETIMEOUT=10
  # ZBX_ENABLE_SNMP_TRAPS=true
  # ZBX_SOURCEIP=
  # ZBX_HOUSEKEEPINGFREQUENCY=1
  # ZBX_MAXHOUSEKEEPERDELETE=5000
  # ZBX_PROBLEMHOUSEKEEPINGFREQUENCY=60
  ZBX_CACHESIZE=8M
  ZBX_CACHEUPDATEFREQUENCY=10
  ZBX_STARTDBSYNCERS=4
  ZBX_HISTORYCACHESIZE=16M
  ZBX_HISTORYINDEXCACHESIZE=4M
  ZBX_HISTORYSTORAGEDATEINDEX=0
  ZBX_TRENDCACHESIZE=4M
  ZBX_TRENDFUNCTIONCACHESIZE=4M
  ZBX_VALUECACHESIZE=8M
  ZBX_TIMEOUT=10
  ZBX_TRAPPERTIMEOUT=300
  ZBX_UNREACHABLEPERIOD=45
  ZBX_UNAVAILABLEDELAY=60
  ZBX_UNREACHABLEDELAY=15
  # ZBX_LOGSLOWQUERIES=3000
  # ZBX_EXPORTFILESIZE=
  ZBX_STARTPROXYPOLLERS=1
  ZBX_PROXYCONFIGFREQUENCY=10
  ZBX_PROXYDATAFREQUENCY=1
  # ZBX_LOADMODULE="dummy1.so,dummy2.so,dummy10.so"
  # ZBX_TLSCAFILE=
  # ZBX_TLSCRLFILE=
  # ZBX_TLSCERTFILE=
  # ZBX_TLSKEYFILE=
  # ZBX_VAULT=HashiCorp # Available since 6.2.0
  # ZBX_VAULTDBPATH=
  # ZBX_VAULTTLSCERTFILE= # Available since 6.2.0
  # ZBX_VAULTTLSKEYFILE= # Available since 6.2.0
  # ZBX_VAULTURL=https://127.0.0.1:8200
  # VAULT_TOKEN=
  # ZBX_STARTREPORTWRITERS=0
  # ZBX_WEBSERVICEURL=http://zabbix-web-service:10053/report
  # ZBX_SERVICEMANAGERSYNCFREQUENCY=60
