---
- name: Check Nvidia lspci present
  ansible.builtin.shell: |
    set -o pipefail ; lspci | grep -i nvidia
  args:
    executable: /bin/bash
  changed_when: false
  register: result
  failed_when: false
    
- name: Set variable nvidia_output
  ansible.builtin.set_fact:
    nvidia_present: "{{ true if result.stdout != '' else false }}"

- name: Create folder
  ansible.builtin.file:
    name: "{{ openwebui_home }}/data"
    state: directory
    owner: "{{ openwebui_user }}"
    group: "{{ openwebui_user }}"
    mode: "0770"

- name: Create docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ openwebui_home }}/docker-compose.yml"
    owner   : "{{ openwebui_user }}"
    group   : "{{ openwebui_user }}"
    mode: "0644"
  notify: Restart openwebui

- name: Create default.env file
  ansible.builtin.copy:
    content : "{{ openwebui_env }}"
    dest    : "{{ openwebui_home }}/default.env"
    owner   : "{{ openwebui_user }}"
    group   : "{{ openwebui_user }}"
    mode    : "0660"
  notify: Restart openwebui

- name: Create service
  ansible.builtin.template:
    src: openwebui.service.j2
    dest: "/etc/systemd/system/openwebui.service"
    owner: root
    group: root
    mode: "0644"
  notify: Restart openwebui
