---
- name: Install zabbix-agent
  apt:
    name:  zabbix-agent
    state: present

- name: Configure zabbix-agent
  template:
    src:    etc/zabbix/zabbix_agentd.conf.j2
    dest:   /etc/zabbix/zabbix_agentd.conf
    owner:  root
    group:  root
    mode:   0644
  notify: restart zabbix-agent