- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: restarted

- name: Restart zabbix-agent
  ansible.builtin.systemd:
    name: zabbix-agent
    enabled: true
    state: restarted
