- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Restart zabbix-agent
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted
