tasks:
  - name: jpeg-xl
    command: cjxl --lossless_jpeg=0 -q 75 {{.folder}}/{{.name}}.{{.extension}} {{.folder}}/{{.name}}-new.jxl && rm {{.folder}}/{{.name}}.{{.extension}}
    extensions:
      - jpeg
      - jpg
      - png
      - pgx
      - pam
      - pnm
      - pgm
      - ppm
      - pfm
      - gif
      - exr

  - name: heic2jxl
    command: ./heic2jxl.sh {{.folder}} {{.name}} {{.extension}}
    extensions:
      - heic
      - heif

  - name: caesium
    command: caesiumclt --keep-dates --exif --quality=85 --output={{.folder}} {{.folder}}/{{.name}}.{{.extension}}
    extensions:
      - jpeg
      - jpg
      - png
      - tiff
      - tif
      - webp
      - gif

  - name: handbrake
    command: HandBrakeCLI --preset-import-file handbrake.json -Z immich-upload-optimizer -i {{.folder}}/{{.name}}.{{.extension}} -o {{.folder}}/{{.name}}-new.mkv && rm {{.folder}}/{{.name}}.{{.extension}}
    extensions:
      - 3gp
      - 3gpp
      - avi
      - flv
      - m4v
      - mkv
      - mts
      - m2ts
      - m2t
      - mp4
      - insv
      - mpg
      - mpe
      - mpeg
      - mov
      - webm
      - wmv

  # Block all other formats from being uploaded.