---
- name: Create user for zabbix
  ansible.builtin.include_role:
    name: daowolf2000.linux.users
  vars:
    users_x:
      zbx:
        uid: 1997
        gid: 1995
        groups: docker
        shell: /bin/false
        password: "!"
        home: "{{ zabbix_path }}"

- name: Set owner for zabbix home
  ansible.builtin.file:
    path: "{{ zabbix_path }}"
    state: directory
    owner: "{{ zabbix_user_uid }}"
    group: "{{ zabbix_user_gid }}"
    recurse: true

- name: Create folders structure for zbx-main
  file:
    path:   "{{ zbx_path }}/{{ item }}"
    owner:  "{{ zbx_user }}"
    group:  "{{ zbx_group }}"
    state:  directory
    mode:   0770
  loop:
    - db
    - srv/enc
    - srv/ssh_keys
    - srv/alertscripts
    - srv/externalscripts
    - srv/dbscripts
    - srv/modules
    - srv/export

- import_tasks: tasks/docker-image-load.yml
  vars: 
    img:  "{{ zbx_db_image }}"
    file: timescaledb.tgz

- import_tasks: tasks/docker-image-load.yml
  vars: 
    img:  "{{ zbx_srv_image }}"
    file: zabbix-server-pgsql.tgz

- name: Copy docker-compose file and cfg
  template:
    src:    "{{ item }}.j2"
    dest:   "{{ zbx_path }}/{{ item }}"
    owner:  "{{ zbx_user }}"
    group:  "{{ zbx_group }}"
    mode:   0660
  loop:
    - srv/docker-compose.yml
    - srv/env_db
    - srv/env_srv
  notify: restart zbx-main

- name: Copy systemd for zbx-main
  template:
    src:    etc/systemd/system/zbx-main.service
    dest:   /etc/systemd/system/zbx-main.service
    owner:  root
    group:  root
    mode:   0644
  notify: restart zbx-main


