---
- name: apt_key | Set repo metadata
  ansible.builtin.set_fact:
    repo_meta_key: "{{ 'signed-by=' ~ repo_key_file }}"

- name: apt_key | Check if matching GPG key already exists.
  ansible.builtin.shell:
    cmd: |-
      # Если файл отсутствует — возвращаем код выхода 2
      [ -f {{ repo_key_file | quote }} ] || exit 2
       # Проверка наличия ключей из файла ключа репозитория
      gpg --list-keys --no-default-keyring --keyring {{ repo_key_file | quote }} {{ repo_key_id or '' }}
      exit $?
  register: should_download_gpg_key
  failed_when: should_download_gpg_key.rc not in (0, 2) # Допустимые коды возврата: успех (0), отсутствие файла (2)
  changed_when: false

- name: apt_key | Add GPG key {{ repo_name }}
  when: should_download_gpg_key.rc != 0
  block:
    - name: apt_key | Create directory for keyring
      ansible.builtin.file:
        path  : '{{ repo_key_path }}'
        state : directory
        owner : root
        group : root
        mode  : '0755'
      become: true
      register: gpg_tempfile

    - name: apt_key | Create temporary file for {{ repo_name }}.
      ansible.builtin.tempfile:
        state: file
      register: gpg_tempfile

    - name: apt_key | Create temporary file for armored {{ repo_name }}.
      ansible.builtin.tempfile:
        state: file
      register: asc_tempfile
      when: repo_key_dearmor

    - name: apt_key | Download GPG key {{ repo_name }}
      ansible.builtin.get_url:
        url   : "{{ repo_key_url }}"
        dest  : "{{ asc_tempfile.path if repo_key_dearmor else gpg_tempfile.path }}"
        mode  : '0600'
        force : true

    - name: apt_key | Dearmor GPG key {{ repo_name }}
      ansible.builtin.command:
        argv:
          - gpg
          # we want to write to the temporary file even though it already exists
          - --yes
          - -o
          - "{{ gpg_tempfile.path | quote }}"
          - --dearmor
          - "{{ asc_tempfile.path | quote }}"
      changed_when: true
      when: repo_key_dearmor

    - name: apt_key | Copy GPG key to {{ repo_key_file }}.
      become: true
      ansible.builtin.copy:
        remote_src: true
        src   : "{{ gpg_tempfile.path }}"
        dest  : "{{ repo_key_file }}"
        owner : root
        group : root
        mode  : '0644'
      register: repo_apt_key_changed

  # Независимо от успеха/неудачи блока выполняем удаление временных файлов
  always: 
    - name: apt_key | Remove temporary file for armored {{ repo_name }}.
      ansible.builtin.file:
        path  : "{{ asc_tempfile.path }}"
        state : absent
      when: repo_key_dearmor

    - name: apt_key | Remove temporary file for {{ repo_name }}.
      ansible.builtin.file:
        path  : "{{ gpg_tempfile.path }}"
        state : absent
