users_all   : {}  # Пользователи общие для всех
users_group : {}  # Пользователи общие для группы хостов
users_host  : {}  # Пользователи данного хоста


# Значения по умолчанию
users_default:
    # Основные параметры
    state           : present             # Добавить / удалить пользователя (present / absent)
    uid             : "{{ omit }}"        # UID пользователя
    gid             : "{{ omit }}"        # GID основной группы пользователя
    group           : "{{ omit }}"        # Имя основной группы пользователя
    groups          : []                  # Перечень групп пользователей
    groups_append   : true                # Добавить groups к имеющимся группам пользователя (иначе только groups)?
    home            : "{{ omit }}"        # Путь к домашнему каталогу
    home_create     : true                # Создать домашний каталог?
    home_move       : true                # Перемещение домашнего католога (если old_home != new_home)
    home_remove     : true                # Удаление домашнего каталога и почты (при state=absent)
    home_force      : true                # Принудительное удаление (при state=absent)
    # Всегда передавай пароль хэшированным и с заданной солью (если не задать соль, то она будет генерироваться автоматически и 
    # пароль будет каждый раз обновляться). Требует `pip install passlib` на localhost.
    # Пример "{{ lookup('env', 'PASSWORD_DEFAULT') | password_hash('sha512','daowolf2000') }}"
    password        : "{{ omit }}"        # Пароль
    password_update : always              # Если пароль не совпадает, то обновить пароль (или on_create - только при создании пользователя)
    shell           : /bin/bash           # Оболочка пользователя
    system          : false               # Системный пользователь?
    comment         : Create from Ansible # Описание пользователя
    # SSH
    ssh_auth_keys   : "{{ omit }}"        # Ключ для добавления в authorized_keys
    # SUDO
    sudo            : false               # Включить sudo
    sudo_nopass     : false               # Разрешить sudo без пароля
    sudo_commands   : [ ALL ]             # Перечень доступных команды
    # DOTFILES
    dotfiles_repo   : "{{ omit }}"        # Git репозиторий, где хранятся dotfiles
    dotfiles_ver    : "{{ omit }}"        # Версия dotfiles
    # PIPX
    # TODO: Install list of pip package use pipx