---
- name: nvidia_ctk | Configure repository
  ansible.builtin.include_role:
    name: daowolf2000.common.repo
  vars:
    repo_name:    "nvidia-container-toolkit"
    repo_source:  "https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH) /"
    repo_key_url: "https://nvidia.github.io/libnvidia-container/gpgkey"
    repo_key_dearmor: true

- name: nvidia_ctk | Install package nvidia-container-toolkit
  ansible.builtin.apt:
    name  : nvidia-container-toolkit
    state : present

- name: nvidia_ctk | Config no-cgroups parameters
  ansible.builtin.lineinfile:
    path: "/etc/nvidia-container-runtime/config.toml"
    regex: '^(\#|\s)*no-cgroups.*$'
    line: "no-cgroups =  {{ docker_nvidia_ctk_no_cgroups | string | lower }}"

- name: nvidia_ctk | Configure Docker for Nvidia CTK
  ansible.builtin.copy:
    content: |
      {
        "default-runtime": "nvidia",
        "runtimes": {
          "nvidia": {
            "path": "nvidia-container-runtime",
            "runtimeArgs": []
          }
        }
      }
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify: Restart docker
