- name: Deploy to {{ target }} # noqa syntax-check[specific]
  hosts: "{{ target }}"
  become: true

  tasks:

    # Базовая настройка
    - ansible.builtin.import_role: { name: daowolf2000.linux.package }
      tags: [ base, package ]
    - ansible.builtin.import_role: { name: daowolf2000.linux.hosts }
      tags: [ base, hosts ]
    - ansible.builtin.import_role: { name: daowolf2000.linux.sshd }
      tags: [ base, sshd ]
    - ansible.builtin.import_role: { name: daowolf2000.linux.users }
      tags: [ base, users ]

    # Применение дополнительных ролей
    - ansible.builtin.include_role: 
        name: "{{ role_item }}"
      loop: "{{ extra_roles | d([]) }}"
      loop_control:
        loop_var: role_item
      tags: [ extra ]

