- name: Deploy to {{ target }} # noqa syntax-check[specific]
  hosts: "{{ target }}"
  become: true

  tasks:

    # Базовая настройка
    - ansible.builtin.import_role: { name: daowolf2000.linux.package }
    - ansible.builtin.import_role: { name: daowolf2000.linux.hosts }
    - ansible.builtin.import_role: { name: daowolf2000.linux.sshd }
    - ansible.builtin.import_role: { name: daowolf2000.linux.users }

    # Применение дополнительных ролей
    - ansible.builtin.include_role: 
        name: "{{ role_item }}"
      loop: "{{ extra_roles | d([]) }}"
      loop_control:
        loop_var: role_item

