---

- name: Configuer sources.list (add {{ package_repo }})
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: '^(deb .* {{ ansible_distribution_release }} main).*$'
    replace: '\1 {{ package_repo }}'
  register: _repo_changed

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    update_cache_retries: 3
    update_cache_retry_max_delay: 3
  when: _repo_changed is changed

- name: Install package
  ansible.builtin.apt:
    name: "{{ item }}"
    lock_timeout: 600
  loop: "{{ package_all + package_group + package_host }}"

