---

- name: Configuer sources.list (add {{ package_repo }})
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: '^(deb .* {{ ansible_distribution_release }} main).*$'
    replace: '\1 {{ package_repo }}'
  register: _repo_changed
  tags: [print_action]

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  when: _repo_changed is changed

- name: Install package
  ansible.builtin.apt:
    name: "{{ package_all + package_group + package_host }}"
  tags: [print_action]
